Fix: max body size option should actually be passed to HttpServer
Error: Max body size option was not honored
Caused by: $options->withMaxBodySize() returns a new instance containing that option, but that instance was not used