Fix concurrency issue in QueueManager::processBatch
Error: Uncaught Amp\Beanstalk\DeadlineSoonException causing the ESB to crash

Caused by: Wrong Beanstalk job deleted at the end of the job
Caused by: Multiple Beanstalk jobs for the same job UUID. With multiple concurrent workers that same job UUID will be assigned to multiple workers. $uuidToBeanstalkIdMap[$job->getUuid()] will then only contain one of the beanstalk job ids, so one of the worker's queue manager won't be able to delete his job after finish.
Caused by: Concurrent calls to QueueManager::processBatch() were possible (and should be possible), but the batch itself was shared over multiple HTTP requests. Causing the same job being inserted twice (or more).

Resolved by: Processing the batch via a local variable instead of the shared property.