Fix ElasticSearch bulk index
Fixes
esb.ERROR: An error occurred producing/queueing jobs. {"producer":"..name..","last_job_payload_data":{..data..},"error":"An error occurred. Response code: 400
{
    \"error\": {
        \"root_cause\": [
            {
                \"type\": \"action_request_validation_exception\",
                \"reason\": \"Validation Failed: 1: type is missing;\"
    },
    \"status\": 400
}","test":false} []

on ElasticSearch version 6.8.8